//
//  Names.m
//  TokenFieldExample
//
//  Created by Tom on 06/03/2010.
//  Copyright 2010 Tom Irving. All rights reserved.
//

#import "Names.h"

@implementation Names

+ (NSArray *)listOfNames {
	
	// Generated with http://www.kleimo.com/random/name.cfm
	
	return [NSArray arrayWithObjects:
			
            @"Acorn squash",
            @"Alfalfa Sprouts",
            @"Anchovies",
            @"Apples",
            @"Artichoke",
            @"Arugula",
            @"Asparagus",
            @"Aubergine",
            @"Avocado",
            @"Bacon",
            @"Baking powder",
            @"Baking soda",
            @"Baking sugar",
            @"Bar sugar",
            @"Basil",
            @"Beans",
            @"Bell peppers",
            @"Blackberries",
            @"Bok choy",
            @"Bread",
            @"Breadfruit",
            @"Broad beans",
            @"Broccoflower",
            @"Broccoli",
            @"Broccoli rabe",
            @"Broccolini",
            @"Brown sugar",
            @"Brussels Sprouts",
            @"Butter",
            @"Butternut pumpkin",
            @"Butternut squash",
            @"Cabbage",
            @"Cactus, Edible",
            @"Calabrese",
            @"Cane sugar",
            @"Capsicum",
            @"Caraway",
            @"Carrot",
            @"Caster sugar",
            @"catfish",
            @"Cauliflower",
            @"Cayenne pepper",
            @"Celeriac",
            @"Celery",
            @"Chard",
            @"Cheese",
            @"Chicory",
            @"Chilli peppers",
            @"Chinese leaves",
            @"Chives",
            @"Chocolate",
            @"Cilantro",
            @"Cinnamon",
            @"Clarified butter",
            @"Coconut",
            @"Coconut milk",
            @"Cod",
            @"Coffee",
            @"Collard greens",
            @"Confectioners' sugar",
            @"Coriander",
            @"Corn",
            @"Corn syrup",
            @"Cottonseed oil",
            @"Courgette",
            @"Cream of tartar",
            @"Cucumber",
            @"Cumin",
            @"Daikon",
            @"Dandelion",
            @"Demerara sugar",
            @"Dough",
            @"Edible Cactus",
            @"Eggplant",
            @"Eggs",
            @"Endive",
            @"Fava Beans",
            @"Fiddlehead ",
            @"Fiddlehead fern",
            @"Five Spice Powder",
            @"Flour",
            @"Frisee",
            @"Fructose",
            @"Fruit sugar",
            @"Ful",
            @"Garam masala",
            @"Garbonzo beans",
            @"Garlic",
            @"Gem squash",
            @"Ghee",
            @"Giblets",
            @"Ginger",
            @"Granulated sugar",
            @"Grape seed oil",
            @"Green beans"
            @"Green onion",
            @"Heart of Palm",
            @"Hemp",
            @"Honey",
            @"Icing sugar",
            @"Isomalt",
            @"Jaggery",
            @"Jams",
            @"Jellies",
            @"Jerusalem artichoke",
            @"Jicama",
            @"Kale", 
            @"Kohlrabi", 
            @"Kumara", 
            @"Leek", 
            @"Lemongrass", 
            @"Lentils", 
            @"Lettuce", 
            @"Liver", 
            @"Maize", 
            @"Maple syrup", 
            @"Meat", 
            @"Milk", 
            @"Mortadella", 
            @"Mussels", 
            @"Nori", 
            @"Nutmeg", 
            @"Nutritional Yeast Flakes", 
            @"Nuts", 
            @"Octopuses", 
            @"Okra", 
            @"Olive", 
            @"Olive oil", 
            @"Onion", 
            @"Orange Blossom Water", 
            @"Oranges", 
            @"Oregano", 
            @"Oysters", 
            @"Panch Puran", 
            @"Paprika", 
            @"Parsley", 
            @"Parsnip", 
            @"Pear", 
            @"Peas", 
            @"Pepper", 
            @"Peppers", 
            @"Plantain", 
            @"Poppy Seeds", 
            @"Potato", 
            @"Potatoes", 
            @"Poultry", 
            @"Powdered sugar", 
            @"Pumpkin", 
            @"Pumpkin Seeds", 
            @"Radish", 
            @"Rape", 
            @"Raw sugar", 
            @"Refined sugar", 
            @"Rice", 
            @"Rice flour", 
            @"Rock sugar", 
            @"Rum", 
            @"Salmon", 
            @"Salt", 
            @"Salt cod", 
            @"Scallion", 
            @"Sesame Seeds", 
            @"Shallot", 
            @"Skate", 
            @"Soybean", 
            @"Spaghetti squash", 
            @"Spek", 
            @"Spinach", 
            @"Spring onion", 
            @"Squash", 
            @"Stockfish", 
            @"Sunchoke", 
            @"Sunflower Seeds", 
            @"Superfine sugar", 
            @"Sweet Potato", 
            @"Sweetcorn", 
            @"Tahini", 
            @"Taro", 
            @"Teff", 
            @"Tomato", 
            @"Trout", 
            @"Tuna", 
            @"Turbanado sugar", 
            @"Turnip", 
            @"Unrefined sugar", 
            @"Vanilla", 
            @"Watercress", 
            @"Watermelon", 
            @"White mushroom", 
            @"White sugar", 
            @"Xanthan gum", 
            @"Yam", 
            @"Yeast", 
            @"Zucchini", 
			nil];
}

@end