//
//  Names.m
//  TokenFieldExample
//
//  Created by Tom on 06/03/2010.
//  Copyright 2010 Tom Irving. All rights reserved.
//

#import "Names.h"

@implementation Names

+ (NSArray *)listOfNames {
	
	// Generated with http://www.kleimo.com/random/name.cfm
	
	return [NSArray arrayWithObjects:
			
            @"acorn squash",
            @"alfalfa sprouts",
            @"anchovies",
            @"apples",
            @"artichoke",
            @"arugula",
            @"asparagus",
            @"aubergine",
            @"avocado",
            @"bacon",
            @"baking powder",
            @"baking soda",
            @"baking sugar",
            @"bar sugar",
            @"basil",
            @"beans",
            @"bell peppers",
            @"blackberries",
            @"bok choy",
            @"bread",
            @"breadfruit",
            @"broad beans",
            @"broccoflower",
            @"broccoli",
            @"broccoli rabe",
            @"broccolini",
            @"brown sugar",
            @"brussels sprouts",
            @"butter",
            @"butternut pumpkin",
            @"butternut squash",
            @"cabbage",
            @"calabrese",
            @"cane sugar",
            @"capsicum",
            @"caraway",
            @"carrot",
            @"caster sugar",
            @"catfish",
            @"cauliflower",
            @"cayenne pepper",
            @"celeriac",
            @"celery",
            @"chard",
            @"cheese",
            @"chicory",
            @"chilli peppers",
            @"chinese leaves",
            @"chives",
            @"chocolate",
            @"cilantro",
            @"cinnamon",
            @"clarified butter",
            @"coconut",
            @"coconut milk",
            @"cod",
            @"coffee",
            @"collard greens",
            @"confectioners' sugar",
            @"coriander",
            @"corn",
            @"corn syrup",
            @"cottonseed oil",
            @"courgette",
            @"cream of tartar",
            @"cucumber",
            @"cumin",
            @"daikon",
            @"dandelion",
            @"demerara sugar",
            @"dough",
            @"edible cactus",
            @"eggplant",
            @"eggs",
            @"endive",
            @"fava beans",
            @"fiddlehead ",
            @"fiddlehead fern",
            @"five spice powder",
            @"flour",
            @"frisee",
            @"fructose",
            @"fruit sugar",
            @"ful",
            @"garam masala",
            @"garbonzo beans",
            @"garlic",
            @"gem squash",
            @"ghee",
            @"giblets",
            @"ginger",
            @"granulated sugar",
            @"grape seed oil",
            @"green beans"
            @"green onion",
            @"heart of palm",
            @"hemp",
            @"honey",
            @"icing sugar",
            @"isomalt",
            @"jaggery",
            @"jams",
            @"jellies",
            @"Jerusalem artichoke",
            @"jicama",
            @"kale",
            @"kohlrabi",
            @"kumara",
            @"leek",
            @"lemongrass",
            @"lentils",
            @"lettuce",
            @"liver",
            @"maize",
            @"maple syrup",
            @"meat",
            @"milk",
            @"mortadella",
            @"mussels",
            @"nori",
            @"nutmeg",
            @"nutritional yeast flakes",
            @"nuts",
            @"octopuses",
            @"okra",
            @"olive",
            @"olive oil",
            @"onion",
            @"orange blossom water", 
            @"oranges",
            @"oregano",
            @"oysters",
            @"panch puran",
            @"paprika",
            @"parsley",
            @"parsnip",
            @"pear",
            @"peas",
            @"pepper",
            @"peppers",
            @"plantain",
            @"poppy seeds",
            @"potato",
            @"potatoes",
            @"poultry",
            @"powdered sugar",
            @"pumpkin",
            @"pumpkin seeds",
            @"radish",
            @"rapeseed",
            @"raw sugar",
            @"refined sugar",
            @"rice", 
            @"rice flour",
            @"rock sugar",
            @"rum",
            @"salmon",
            @"salt",
            @"salt cod",
            @"scallion",
            @"sesame seeds",
            @"shallot",
            @"skate",
            @"soybean",
            @"spaghetti squash",
            @"spek",
            @"spinach",
            @"spring onion",
            @"squash",
            @"stockfish",
            @"sunchoke",
            @"sunflower seeds",
            @"superfine sugar",
            @"sweet potato",
            @"sweetcorn",
            @"tahini",
            @"taro",
            @"teff",
            @"tomato",
            @"trout",
            @"tuna",
            @"turbanado sugar",
            @"turnip",
            @"unrefined sugar",
            @"vanilla",
            @"watercress",
            @"watermelon",
            @"white mushroom",
            @"white sugar",
            @"xanthan gum",
            @"yam",
            @"yeast",
            @"zucchini", 
			nil];
}

@end