//
//  Names.m
//  TokenFieldExample
//
//  Created by Tom on 06/03/2010.
//  Copyright 2010 Tom Irving. All rights reserved.
//

#import "Names.h"

@implementation Names

+ (NSArray *)listOfNames {
	
	// Generated with http://www.kleimo.com/random/name.cfm
	
	return [NSArray arrayWithObjects:
			
            @"açai",
            @"acorn squash",
            @"agave nectar",
            @"alfalfa sprouts",
            @"alfredo sauce",
            @"almond butter",
            @"almond extract",
            @"almonds",
            @"almond milk",
            @"amaranth",
            @"anchovies",
            @"angel hair pasta",
            @"angelica",
            @"anise",
            @"aonori",
            @"apple cider vinegar",
            @"apples",
            @"apricot",
            @"arame",
            @"artichoke",
            @"arugula",
            @"asiago cheese",
            @"asparagus",
            @"aubergine",
            @"avocado",
            @"bacon",
            @"baking powder",
            @"baking soda",
            @"balsamic vinegar",
            @"bamboo shoots",
            @"banana",
            @"barbeque sauce",
            @"barley",
            @"basil",
            @"basmati rice",
            @"bay leaf",
            @"beans",
            @"bean sprouts",
            @"beef",
            @"beef broth",
            @"beets",
            @"beet greens",
            @"bell peppers",
            @"bitter melon",
            @"blackberries",
            @"black beans",
            @"blackeye peas",
            @"black pepper",
            @"blood oranges",
            @"blueberries",
            @"blue cheese",
            @"bok choy",
            @"boldo",
            @"borage",
            @"bouillon cubes",
            @"bread",
            @"bread crumbs",
            @"breadfruit",
            @"brie cheese",
            @"broad beans",
            @"broccoflower",
            @"broccoli",
            @"broccoli rabe",
            @"broccolini",
            @"brown rice",
            @"brown sugar",
            @"Brussels sprouts",
            @"butter",
            @"butternut pumpkin",
            @"butternut squash",
            @"cabbage",
            @"calabrese",
            @"camembert cheese",
            @"camphor",
            @"cane sugar",
            @"cannellini beans",
            @"canola oil",
            @"cantaloupe",
            @"caper",
            @"capsicum",
            @"caraway",
            @"cardamom",
            @"cardoon",
            @"carola",
            @"carrot",
            @"caster sugar",
            @"catfish",
            @"cauliflower",
            @"cayenne pepper",
            @"celeriac",
            @"celery",
            @"celery seeds",
            @"chard",
            @"cheddar cheese",
            @"cheese",
            @"cherries",
            @"cherry tomatoes",
            @"chervil",
            @"chia seeds",
            @"chicken",
            @"chicken broth", 
            @"chickpeas",
            @"chicory",
            @"chilli peppers",
            @"chinese leaves",
            @"chives",
            @"chocolate",
            @"chutney",
            @"cicely",
            @"cilantro",
            @"cinnamon",
            @"clams",
            @"clarified butter",
            @"clementine",
            @"cocoa powder",
            @"coconut",
            @"coconut flakes",
            @"coconut milk",
            @"coconut oil",
            @"cod",
            @"coffee",
            @"cole slaw",
            @"collard greens",
            @"confectioners' sugar",
            @"coriander",
            @"corn",
            @"corn meal",
            @"corn oil",
            @"corn syrup",
            @"cottage cheese",
            @"cottonseed oil",
            @"courgette",
            @"courgette flower",
            @"crab",
            @"cranberries",
            @"cream cheese",
            @"cream of tartar",
            @"crème fraîche",
            @"cress",
            @"crimini mushrooms",
            @"croutons",
            @"cucumber",
            @"cumin",
            @"currant",
            @"curry paste",
            @"curry powder",
            @"curry leaf",
            @"daikon",
            @"dandelion",
            @"dates",
            @"deli mustard",
            @"demerara sugar",
            @"Dijon mustard",
            @"dill",
            @"dill seed",
            @"dragonfruit",
            @"dough",
            @"edible cactus",
            @"egg noodles",
            @"eggplant",
            @"eggs",
            @"elderberry",
            @"endive",
            @"epazote",
            @"farfalle pasta",
            @"fava beans",
            @"fennel",
            @"fettuccine",
            @"fiddlehead ",
            @"fiddlehead fern",
            @"fig",
            @"fingerling potatoes",
            @"fish",
            @"five spice powder",
            @"flour",
            @"frisee",
            @"fructose",
            @"fruit sugar",
            @"ful",
            @"galangal",
            @"garam masala",
            @"garbonzo beans",
            @"garlic",
            @"gem squash",
            @"ghee",
            @"giblets",
            @"ginger",
            @"gnocchi",
            @"goat cheese",
            @"gouda cheese",
            @"granulated sugar",
            @"grapefruit",
            @"grapes",
            @"grape seed oil",
            @"Greek yogurt",
            @"green beans",
            @"green bell pepper",
            @"green chard",
            @"green grapes",
            @"green onion",
            @"guava",
            @"ham",
            @"hazelnut",
            @"hazelnut chocolate spread",
            @"heart of palm",
            @"hemp",
            @"honey",
            @"honeydew",
            @"horseradish",
            @"hot sauce",
            @"icing sugar",
            @"isomalt",
            @"Italian dressing",
            @"jack cheese",
            @"jaggery",
            @"jalapeno peppers",
            @"jams",
            @"jasmine rice",
            @"jellies",
            @"Jerusalem artichoke",
            @"jicama",
            @"juniper berry",
            @"kale",
            @"ketchup",
            @"kidney beans",
            @"kiwi",
            @"kohlrabi",
            @"kokum",
            @"korarima",
            @"kumara",
            @"kumquat",
            @"kurrat",
            @"lamb",
            @"lasagne pasta",
            @"lavender",
            @"leek",
            @"lemon",
            @"lemongrass",
            @"lentils",
            @"lettuce",
            @"lima beans",
            @"lime",
            @"linguine",
            @"liver",
            @"lotus root",
            @"macadamia nuts",
            @"macaroni pasta",
            @"maize",
            @"mango",
            @"maple syrup",
            @"margarine",
            @"marinara sauce",
            @"mascarpone cheese",
            @"mayonaise",
            @"meat",
            @"milk",
            @"mint",
            @"mortadella",
            @"mozzarella cheese",
            @"mulberry",
            @"mushrooms",
            @"mussels",
            @"mustard",
            @"mustard greens",
            @"nectarine",
            @"new potatoes",
            @"nopal",
            @"nori",
            @"nutmeg",
            @"nutritional yeast flakes",
            @"nuts",
            @"octopuses",
            @"okra",
            @"olive",
            @"olive oil",
            @"onion",
            @"orange bell pepper",
            @"orange blossom water", 
            @"oranges",
            @"oregano",
            @"orzo",
            @"oysters",
            @"oyster sauce",
            @"panch puran",
            @"paprika",
            @"parmesan cheese",
            @"parsley",
            @"parsnip",
            @"passion fruit",
            @"pasta shells",
            @"peach",
            @"peanut butter",
            @"peanut oil",
            @"peanuts",
            @"pear",
            @"pearl onion",
            @"peas",
            @"pecans",
            @"penne",
            @"pepper",
            @"pepper jack cheese",
            @"pepperoncini",
            @"peppers",
            @"persimmon",
            @"pesto",
            @"pickles",
            @"pineapple",
            @"pine nuts",
            @"pinto beans",
            @"pistachio",
            @"pizza dough",
            @"plantain",
            @"plum",
            @"polenta",
            @"pomegranate",
            @"pomelo",
            @"poppy seeds",
            @"pork",
            @"portabello mushrooms",
            @"potato",
            @"potato onion",
            @"potatoes",
            @"poultry",
            @"powdered sugar",
            @"prawns",
            @"pumpkin",
            @"pumpkin seeds",
            @"quince",
            @"quinoa",
            @"radicchio",
            @"radish",
            @"raisins",
            @"ranch dressing",
            @"rapeseed",
            @"raspberry",
            @"ravioli",
            @"raw sugar",
            @"red bell pepper",
            @"red chard",
            @"red grapes",
            @"red onion",
            @"red pepper flakes",
            @"red plum",
            @"red potato",
            @"red wine",
            @"red wine vinegar",
            @"refined sugar",
            @"relish",
            @"rhubarb",
            @"rice", 
            @"rice flour",
            @"rice paper",
            @"rice vinegar",
            @"ricotta cheese",
            @"rigatoni",
            @"rosemary",
            @"rum",
            @"rutabagas",
            @"saffron",
            @"sage",
            @"salami",
            @"salmon",
            @"salsa",
            @"salt",
            @"salt cod",
            @"sardines",
            @"scallion",
            @"scallops",
            @"seaweed",
            @"sesame oil",
            @"sesame seeds",
            @"shallot",
            @"shiitake mushrooms",
            @"shrimp",
            @"skate",
            @"snap peas",
            @"snow peas",
            @"sorrel",
            @"sour cream",
            @"soybean",
            @"soy milk",
            @"soy sauce",
            @"spaghetti",
            @"spaghetti squash",
            @"spek",
            @"spinach",
            @"spring onion",
            @"squash",
            @"stockfish",
            @"strawberries",
            @"sugar",
            @"sunchoke",
            @"sun dried tomatoes",
            @"sunflower seeds",
            @"superfine sugar",
            @"sweet potato",
            @"sweetcorn",
            @"Swiss chard",
            @"Swiss cheese",
            @"Tabasco sauce",
            @"tahini",
            @"tangerine",
            @"taro",
            @"tarragon",
            @"teff",
            @"teriyaki sauce",
            @"Thai basil",
            @"thyme",
            @"tofu",
            @"tomatillo",
            @"tomato",
            @"tomato sauce",
            @"tortellini",
            @"tortilla",
            @"trout",
            @"truffle oil",
            @"truffles",
            @"tuna",
            @"turbanado sugar",
            @"turkey",
            @"turmeric",
            @"turnip",
            @"turnip greens",
            @"unrefined sugar",
            @"vanilla",
            @"vanilla beans",
            @"vanilla extract",
            @"veal",
            @"vegetable broth",
            @"vegetable oil",
            @"vermicelli",
            @"vinegar",
            @"walnuts",
            @"wakame",
            @"wasabi",
            @"water chestnuts",
            @"watercress",
            @"watermelon",
            @"white beans",
            @"white corn",
            @"white mushrooms",
            @"white onion",
            @"white peach",
            @"white pepper",
            @"white rice",
            @"white sugar",
            @"white vinegar",
            @"white wine",
            @"winter melon",
            @"xanthan gum",
            @"yam",
            @"yeast",
            @"yellow bell pepper",
            @"yellow mustard",
            @"yellow onion",
            @"yogurt",
            @"zucchini", 
			nil];
}

@end